Repository gitflow-incremental-builder/gitflow-incremental-builder, pull requests merged in 2022-11, with the labels that each got.

#582 Fix IAE if 'src' exists in root and make sure to check for pom.xml
  src/main/java/io/github/gitflowincrementalbuilder/ChangedProjects.java
  src/test/java/io/github/gitflowincrementalbuilder/BaseChangedProjectsTest.java
Labels: bug

#584 Lower warnings in ChangedProjects to DEBUG
  src/main/java/io/github/gitflowincrementalbuilder/ChangedProjects.java
Labels: enhancement

#585 Avoid JavaDoc 'warning: no comment' spam on Java 17
  pom.xml
Labels: build

#586 Fix examples in *Matches/Matching docs
  README.md
Labels: documentation

#588 Fix or suppress deprecation warnings
  pom.xml
  src/main/java/io/github/gitflowincrementalbuilder/mojo/MojoParametersGeneratingByteBuddyPlugin.java
  src/test/java/io/github/gitflowincrementalbuilder/BaseUnchangedProjectsRemoverTest.java
  src/test/java/io/github/gitflowincrementalbuilder/UnchangedProjectsRemoverTest.java
  src/test/java/io/github/gitflowincrementalbuilder/mocks/JGitIsolation.java
  src/test/java/io/github/gitflowincrementalbuilder/mocks/MavenSessionMock.java
Labels: housekeeping

#587 Introduce `argsForDownstreamModules`
  README.md
  pom.xml
  src/main/java/io/github/gitflowincrementalbuilder/UnchangedProjectsRemover.java
  src/main/java/io/github/gitflowincrementalbuilder/config/Configuration.java
  src/main/java/io/github/gitflowincrementalbuilder/config/Property.java
  src/test/java/io/github/gitflowincrementalbuilder/UnchangedProjectsRemoverTest.java
Labels: new feature

#604 Remove MNG-6173 handling from integration tests
  src/test/java/io/github/gitflowincrementalbuilder/integration/MavenIntegrationTestBase.java
Labels: housekeeping

#607 fix: handle case of no defined configuration in maven-jar-plugin test…
  src/main/java/io/github/gitflowincrementalbuilder/DownstreamCalculator.java
Labels: bug
